setup:
  examples:
    - input: We develop chips for the automotive industry, such as$
      output: ''
  context: ''
  parameterValues:
    Offering type: Product
    Product: >-
      An IP core that can be deployed on any chip, thus giving AI
      functionalities to any device. Unlike 90% of competitors, our product has
      already been tested in silicon (not just simulations) and has shown some
      impressive results. Here’s an excerpt about us from the respectable Linley
      Group’s Microprocessor Report: “In the market segments Edged.AI is
      targeting, we expect standalone-DLA [deap learning accelerator] chips will
      quickly give way to SoCs [systems on chip] that integrate a DLA. But
      developing the latter consumes more time and money, putting it beyond the
      reach of many startups, particularly new entrants coming late to the game.
      Edged wisely abandoned its early ambitions as a chip vendor, instead using
      IP to serve SoC vendors and others needing DLAs for internal chip
      designs.”
    Business: >-
      We are Edged.ai, a small startup that designs AI cores for tensor
      processing units.
    Service: ''
    Feature: ''
display:
  name: Edged.ai
  inputCaption: Tell a few words about yourself
  inputPlaceholder: I am a … who does … and loves … — or anything else you can come up with.
  outputCaption: Here’s what you can do
template:
  apiKey: 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
  inputPrefix: Customer profile
  outputPrefix: Suggestions
  parameters:
    - type: text
      name: Business
      recital: true
      multiline: true
    - type: choices
      caption: Offering type
      name: Offering type
      choices:
        - Product
        - Feature
        - Service
    - name: Product
      type: text
      recital: true
      requires: Offering type
      regex: ^Product|Feature$
      multiline: true
    - type: text
      name: Feature
      requires: Offering type
      recital: true
      regex: ^Feature$
      multiline: true
    - type: text
      name: Service
      recital: true
      requires: Offering type
      regex: ^Service$
      multiline: true
  instruction: >-
    Suggest uses for an offering based on its description and a customer
    profile.
name: Edged.ai
id: 1634843315317x809437390242563100
